//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExamApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayType
    {
        public PayType()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
